using System.Diagnostics;

namespace Purity.Utilities
{
	/// <summary>
	/// Uses <see cref="DateTime"/> to track time and calculate time related values/timers.
	/// </summary>
	public static class Time
	{
		/// <summary>
		/// The type of time convertion going from one time unit to another.
		/// This is used by <see cref="ConvertToTime"/>.
		/// </summary>
		public enum Convertion
		{
#pragma warning disable CS1591
			MillisecondsToSeconds, MillisecondsToMinutes,
			SecondsToMilliseconds, SecondsToMinutes, SecondsToHours,
			MinutesToMilliseconds, MinutesToSeconds, MinutesToHours, MinutesToDays,
			HoursToSeconds, HoursToMinutes, HoursToDays, HoursToWeeks,
			DaysToMinutes, DaysToHours, DaysToWeeks,
			WeeksToHours, WeeksToDays
#pragma warning restore CS1591
		}
		/// <summary>
		/// A unit, used to measure a time period. Used by <see cref="ConvertToClock"/>.
		/// </summary>
		[Flags]
		public enum Unit
		{
#pragma warning disable CS1591
			Day = 1,
			Hour = 2,
			Minute = 4,
			Second = 8,
			Millisecond = 16,
			AM_PM = 32,
			DisplayAM_PM = 64,
#pragma warning restore CS1591
		}

		/// <summary>
		/// The real time clock taken from <see cref="DateTime.Now"/> in seconds ranged
		/// [0 - 86399]<br></br>or in clock hours ranged [12 AM/00:00/24:00 - 11:59:59 AM/23:59:59].
		/// </summary>
		public static float Clock { get; private set; }
		/// <summary>
		/// Limits the <see cref="Delta"/> (default is 0.1 which is 10 updates per second).
		/// This prevents huge values generated by long periods of not calling <see cref="Update"/>
		/// (the application lagging or the user dragging the window for example).
		/// </summary>
		public static float MaxDelta { get; set; } = 0.1f;
		/// <summary>
		/// The time in seconds since the last <see cref="Update"/> call, limited by
		/// <see cref="MaxDelta"/>. This is useful for multiplying it with a step value in
		/// continuous calculations so that the step value is consistent on all systems.
		/// </summary>
		public static float Delta { get; private set; }
		/// <summary>
		/// The unlimited time in seconds since the last <see cref="Update"/> call. Same as
		/// <see cref="Delta"/> but not limited by <see cref="MaxDelta"/>. Useful making for timers.
		/// </summary>
		public static float RawDelta { get; private set; }
		/// <summary>
		/// The amount of <see cref="Update"/> calls per second.
		/// </summary>
		public static float UpdatesPerSecond { get; private set; }
		/// <summary>
		/// The average <see cref="UpdatesPerSecond"/> since the start of the application.
		/// </summary>
		public static float UpdatesPerSecondAverage { get; private set; }
		/// <summary>
		/// The seconds passed since the start of the application.
		/// </summary>
		public static float RuntimeClock { get; private set; }
		/// <summary>
		/// The amount of <see cref="Update"/> calls since the start of the application.
		/// </summary>
		public static uint UpdateCount { get; private set; }

		/// <summary>
		/// Updates all values, timers and schedulers.
		/// </summary>
		public static void Update()
		{
			var delta = (float)dt.Elapsed.TotalSeconds;
			RawDelta = delta;
			Delta = Math.Clamp(delta, 0, MathF.Max(0, MaxDelta));
			dt.Restart();

			Clock = Now;
			RuntimeClock += Delta;
			UpdatesPerSecond = 1f / Delta;
			UpdatesPerSecondAverage = UpdateCount / RuntimeClock;
			UpdateCount++;

			var toBeRemoved = new List<Timer>();
			for(int i = 0; i < timers.Count; i++)
			{
				var timer = timers[i];

				timer.TryTrigger(delta);

				if(timer.IsDisposed)
					toBeRemoved.Add(timer);
			}
			for(int i = 0; i < toBeRemoved.Count; i++)
			{
				var timer = toBeRemoved[i];
				timers.Remove(timer);
			}

		}

		/// <summary>
		/// Uses <see cref="System.TimeSpan"/> to convert <paramref name="seconds"/>
		/// into a clock/timer <see cref="string"/> with an optional <paramref name="separator"/>
		/// including multiple <paramref name="units"/>. Returns the result afterwards.
		/// </summary>
		public static string ClockFrom(this float seconds, string separator = ":",
			Unit units = Unit.Hour | Unit.Minute | Unit.Second)
		{
			var ts = TimeSpan.FromSeconds(seconds);
			var result = "";
			var counter = 0;

			if(units.HasFlag(Unit.Day))
			{
				var val = (int)ts.TotalDays;
				result += $"{val:D2}";
				counter++;
			}
			if(units.HasFlag(Unit.Hour))
			{
				var sep = counter > 0 ? separator : "";
				var val = counter == 0 ? (int)ts.TotalHours :
					(units.HasFlag(Unit.AM_PM) ? (int)Wrap(ts.Hours, 12) : ts.Hours);
				val = val == 0 ? 12 : val;
				result += $"{sep}{val:D2}";
				counter++;
			}
			if(units.HasFlag(Unit.Minute))
			{
				var sep = counter > 0 ? separator : "";
				var val = counter == 0 ? (int)ts.TotalMinutes : ts.Minutes;
				result += $"{sep}{val:D2}";
				counter++;
			}
			if(units.HasFlag(Unit.Second))
			{
				var sep = counter > 0 ? separator : "";
				var val = counter == 0 ? (int)ts.TotalSeconds : ts.Seconds;
				result += $"{sep}{val:D2}";
				counter++;
			}
			if(units.HasFlag(Unit.Millisecond))
			{
				var val = counter == 0 ? (int)ts.TotalMilliseconds : ts.Milliseconds;
				var dot = units.HasFlag(Unit.Second) ? "." : "";
				var sep = dot == "" && counter > 0 ? separator : "";
				result += $"{sep}{dot}{val:D3}";
				counter++;
			}
			if(units.HasFlag(Unit.DisplayAM_PM))
			{
				var sep = counter > 0 ? " " : "";
				var str = ts.Hours >= 12 ? "PM" : "AM";
				result += $"{sep}{str}";
			}
			return result;

			float Wrap(float number, float range)
			{
				return ((number % range) + range) % range;
			}
		}
		/// <summary>
		/// Converts <paramref name="time"/> from one unit to another
		/// (chosen by <paramref name="convertType"/>) and returns the result.
		/// </summary>
		public static float TimeFrom(this float time, Convertion convertType)
		{
			return convertType switch
			{
				Convertion.MillisecondsToSeconds => time / 1000,
				Convertion.MillisecondsToMinutes => time / 1000 / 60,
				Convertion.SecondsToMilliseconds => time * 1000,
				Convertion.SecondsToMinutes => time / 60,
				Convertion.SecondsToHours => time / 3600,
				Convertion.MinutesToMilliseconds => time * 60000,
				Convertion.MinutesToSeconds => time * 60,
				Convertion.MinutesToHours => time / 60,
				Convertion.MinutesToDays => time / 1440,
				Convertion.HoursToSeconds => time * 3600,
				Convertion.HoursToMinutes => time * 60,
				Convertion.HoursToDays => time / 24,
				Convertion.HoursToWeeks => time / 168,
				Convertion.DaysToMinutes => time * 1440,
				Convertion.DaysToHours => time * 24,
				Convertion.DaysToWeeks => time / 7,
				Convertion.WeeksToHours => time * 168,
				Convertion.WeeksToDays => time * 7,
				_ => 0,
			};
		}

		/// <summary>
		/// Schedules a call to a provided <paramref name="method"/> after a certain amount of <paramref name="seconds"/>.
		/// May also call it continuously every few <paramref name="seconds"/> if it <paramref name="isRepeating"/>. In other words:
		/// subscribes a <paramref name="method"/> to a timer.
		/// </summary>
		public static void CallAfter(float seconds, Action method, bool isRepeating = false)
		{
			timers.Add(new Timer(seconds, isRepeating, method));
		}
		/// <summary>
		/// Cancel any scheduled calls to a certain <paramref name="method"/>. In other words: unsubscribes a method from a timer.
		/// </summary>
		public static void CancelCall(Action method)
		{
			var timersToRemove = new List<Timer>();
			for(int i = 0; i < timers.Count; i++)
				if(timers[i].method == method)
					timersToRemove.Add(timers[i]);

			for(int i = 0; i < timersToRemove.Count; i++)
				timers.Remove(timersToRemove[i]);
		}
		/// <summary>
		/// Offsets the call time of a scheduled <paramref name="method"/> by <paramref name="seconds"/>.
		/// </summary>
		public static void OffsetCall(float seconds, Action method)
		{
			for(int i = 0; i < timers.Count; i++)
				if(timers[i].method == method)
					timers[i].delay += seconds;
		}

		#region Backend
		private class Timer
		{
			public Action? method;
			public float time;
			public bool isLooping;
			public float delay;
			public bool IsDisposed => method == null;

			public Timer(float seconds, bool isLooping, Action method)
			{
				delay = seconds;
				this.isLooping = isLooping;
				this.method = method;
			}

			public void TryTrigger(float delta)
			{
				time += delta;

				if(time < delay)
					return;

				Trigger(true);

				if(isLooping == false)
					Dispose();
			}
			public void Restart()
			{
				time = 0;
			}
			public void Trigger(bool reset)
			{
				method?.Invoke();

				if(reset)
					Restart();
			}

			private void Dispose()
			{
				method = null;
			}
		}

		private static readonly List<Timer> timers = new();
		private static readonly Stopwatch dt = new();

		private static float Now => (float)DateTime.Now.TimeOfDay.TotalSeconds;
		#endregion
	}
}
